language: python
cache:
  directories:
  - "${HOME}/.cache"
env:
  - AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-west-2
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: false
install:
  - pip install .
  - pip install pytest pytest-runner
script:
  - python setup.py test
deploy:
  - provider: pypi
    user: cleardataeng
    password:
      secure: DhK0AwKrYqmGDRT9xVmQJOZPhRA4D4ckk0zO8yvmGP+X7/2MAna5CCF8bPUh94ucAjkko9sVbAMdzoQ0KC5xtPJHTk2rcBWibl11G77+aRacHVnsu2MHCfJBxOkuIeWkCZCJMaItcs/rxBsnedYNp30YDLaUjDivXiAPKK/nP+El0LKjLkAW3LmTZTaewECkUTRP2u2SfdqW38GS79dGC4Zmgt5HpX/sIid72lnuM/J7hCYH4OELGZ33e7Yq+zp4DowyUtTrjYPsAuVPZsrM1heGcw8Slp3823mDhh1W4Ysq2hPWFYf+pjmjQoRsEhh9Fzw7dNhKrW3szzWWIsirFwB/CrQr04vVdcUEydy0PZ6uo0QUjvrDGDQOcYUs8KeETJAQ8wghZuaeo99I0qA2f6y7he9/zeguvITdOZHvQzSR6iA2gP7rPcRfjvRL3xuHTWYkcCa7jwuTNe0cFL6YAFuokM5An5TBjLaJ0YsBQsYikefF8+syflyBvln4WwlgJDQv5NEVP02kscxxDnRi6D31QWZwOi0Uv3JnsyfisvYeKjtJcsUBUm1B/6MksQYwvgqst219A/pp15ch+eZP2zE5KOO9t7L78EnvR1j0Es2wsRv/7lAb2UbVlNC2cu9nTc5WW0fAE4V4P0/2jza1YSvavaeQ4XXj3FXWw3ILLKs=
    skip_existing: true
    on:
      tags: true
      branch: master
  - provider: pypi
    user: cleardataeng
    server: https://test.pypi.org/legacy/
    password:
      secure: vRzIlzgJqWoh40M/GlZ1CfrnaWndunw2PcfAYWK9i/K/9zGd+12fUIy952EkMMYzPVubCvNjKE3fYusqm40968z6h7L6Db/S1g4ZHwYdGFKWqOsUFsL7O2rbNAaVW2nGwlswOW3z/+JCPJt8ayDkAjOM3Ey1LROF+AKktFp7297wOU+xE2fTgAkl1UQN2MyqIu2+lkJrMMn/l/rxjOVirYDyMIZJEp0Igm+qUwWfFUb17rpqqAeVCKmnFX4YdSJM5V4rXZBhLFYfkXQx0ZCWlMdAzc8ngBQdmf7DWZfDUuA0nN6Z4+YQw637pjDsahGW7KKxrRRLM9YDJzTobD0kmjM4EU6DBqXJNWRiOxxF1PdKBINhsEDbeHhGvDQ7Rm0lmrEH4mKE0vjp7/fByzsuVa9EgTN9qwZGek0PTI9dRSuWZzIrkEVfICJ1+bfktVt92wPaWY05rJ6kcMT42s5cW2WS2aUfzzn8hhDWMWNXZFpnG87A/HSn+7zvcTtC4/qSm0HD8lHlpqcWtkalgbPbm1nvrnAfp0ldTviW/GvTkzPvUZv5srCBzos7Vx82czwqTjwpZPvbVwKxp0+/cX+iXZ7gTDEGVyGZFsKSl9+oYuT4Drsdy0nybc55/TKSg3N0fPMFRjn/MOhjUPs5WzlDI8LnE07qWHzTPAh7iQubh0s=
    skip_existing: true
    on:
      branch: develop
